# https://github.com/rubocop-hq/rubocop/blob/36404b40cbdac743b596c8520877c4ca3eee5691/manual/cops.md

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - config/environment.rb
    - apps/web/application.rb
    - vendor/**/*
    - node_modules/**/*
    - bin/**/*
  NewCops: enable
  SuggestExtensions: false

Layout/ParameterAlignment:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/FirstParameterIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented

Lint/MissingCopEnableDirective:
  Enabled: false

Style/BlockComments:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Layout/LineLength:
  Max: 100

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
