require: rubocop-rspec

# https://github.com/rubocop-hq/rubocop/blob/36404b40cbdac743b596c8520877c4ca3eee5691/manual/cops.md

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - config/environment.rb
    - apps/web/application.rb
Layout/AlignParameters:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/FirstParameterIndentation:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Layout/IndentArray:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented

Lint/MissingCopEnableDirective:
  Enabled: false

Style/BlockComments:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/LineLength:
  Max: 100

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# rubocop-rspec cops

Capybara/FeatureMethods:
  Enabled: false

FactoryBot/CreateList:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
